/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useControls } from 'leva'
import { extend, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { MeshTransmissionMaterial, shaderMaterial } from '@react-three/drei'
import vertexShader from '../shaders/waves/wave.vert?raw'
import fragmentShader from '../shaders/waves/wave.frag?raw'
import * as THREE from 'three'

const WaveMaterial = shaderMaterial(
    { uTime: 0 },
    vertexShader,
    fragmentShader
)

extend({ WaveMaterial })

export default function Model(props) {
    const { nodes, materials } = useGLTF('./models/Temple/Temple.glb')
    const waveRefs = [useRef(), useRef(), useRef(), useRef(), useRef(), useRef(), useRef(), useRef(), useRef(), 
        useRef(), useRef(), useRef(), useRef(), useRef(), useRef(), useRef()]

    // const materialProps = useControls({
    //     thickness: { value: 1.2 , min: 0, max: 3, step: 0.05 },
    //     roughness: { value: 0, min: 0, max: 1, step: 0.1 },
    //     transmission: { value: 1, min: 0, max: 1, step: 0.1 },
    //     ior: { value: 1.2, min: 0, max: 3, step: 0.1 },
    //     chromaticAberration: { value: 0.02, min: 0, max: 1},
    // })

    useFrame((state) => {
        waveRefs.forEach(ref => {
            if (ref.current) ref.current.uTime = state.clock.elapsedTime
        })
    })

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support.geometry}
          material={materials['standardSurface1.001']}
          position={[3.596, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support1.geometry}
          material={materials['standardSurface1.001']}
          position={[-4.54, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support2.geometry}
          material={materials['standardSurface1.001']}
          position={[-3.523, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support3.geometry}
          material={materials['standardSurface1.001']}
          position={[-2.506, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support4.geometry}
          material={materials['standardSurface1.001']}
          position={[-1.489, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support5.geometry}
          material={materials['standardSurface1.001']}
          position={[-0.472, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support6.geometry}
          material={materials['standardSurface1.001']}
          position={[0.545, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support7.geometry}
          material={materials['standardSurface1.001']}
          position={[1.562, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support8.geometry}
          material={materials['standardSurface1.001']}
          position={[2.579, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Flooring.geometry}
          material={materials['standardSurface1.001']}
          position={[-0.074, 6.148, 0.203]}
          rotation={[-2.813, 0, 0]}
          scale={[38.281, 12.496, 33.795]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1.geometry}
          material={materials['standardSurface1.001']}
          position={[-0.039, 0, -2.551]}
          scale={[23.909, 0.1, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube2.geometry}
          material={materials['standardSurface1.001']}
          position={[-0.039, 0, -2.265]}
          scale={[24.265, 0.069, 0.069]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3.geometry}
          material={materials['standardSurface1.001']}
          position={[-0.039, 0, -1.999]}
          scale={[24.265, 0.069, 0.069]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube4.geometry}
          material={materials['standardSurface1.001']}
          position={[-5.456, 0, -1.502]}
          rotation={[0, 1.571, 0]}
          scale={[38.849, 0.188, 0.165]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5.geometry}
          material={materials['standardSurface1.001']}
          position={[4.573, 0, -1.502]}
          rotation={[0, 1.571, 0]}
          scale={[38.849, 0.188, 0.165]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube6.geometry}
          material={materials['standardSurface1.001']}
          position={[-0.039, 0, -9.496]}
          scale={[28.811, 0.12, 0.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube7.geometry}
          material={materials['standardSurface1.001']}
          position={[-5.456, 0, -10.295]}
          scale={[0.865, 0.27, 0.181]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8.geometry}
          material={materials['standardSurface1.001']}
          position={[4.576, 0, -10.295]}
          scale={[0.865, 0.27, 0.181]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roof.geometry}
          material={materials['standardSurface1.001']}
          position={[-0.039, 5.713, -10.354]}
          scale={[48.497, 12.496, 42.674]}
        />
      </group>
      <group position={[0.264, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group scale={0.895}>
          <group position={[-4.93, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass013.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[0.978, 0, -6.288]} rotation={[0, 0, -0.149]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass004.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[1.738, 0, -6.288]} rotation={[0, 0, -0.104]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass003.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[3.257, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass002.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[3.988, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass001.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[-4.194, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass012.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[-3.462, 0, -6.218]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass011.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[-0.554, 0, -6.288]} rotation={[0, 0, -0.117]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass010.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[-1.283, 0, -6.288]} rotation={[0, 0, -0.128]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass009.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[-2.731, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass008.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[-2, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass007.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[0.194, 0, -6.288]} rotation={[0.012, 0.002, -0.35]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass006.geometry}
              material={materials['standardSurface1.003']}
              position={[0.05, -0.081, -7.948]}
              scale={[1, 1, 0.927]}
            />
          </group>
          <group position={[2.488, 0, -6.288]} rotation={[0, 0, -0.402]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass005.geometry}
              material={materials['standardSurface1.003']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
        </group>
      </group>
      <group position={[0.264, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[-5.043, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1014.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[-4.411, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1013.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[11]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1013.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[0.875, 0, -5.627]} rotation={[0, 0, -0.149]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1004.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[12]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1004.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[1.555, 0, -5.627]} rotation={[0, 0, -0.104]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1003.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[13]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1003.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[2.914, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1002.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[15]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1002.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[3.569, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1001.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[9]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1001.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[-3.753, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1012.geometry}
            material={materials['standardSurface1.004']}
            position={[0.026, -0.067, -4.974]}
            rotation={[1.386, -0.022, -0.1]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[2]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1012.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[-3.098, 0, -5.564]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1011.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[0]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1011.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[-0.496, 0, -5.627]} rotation={[0, 0, -0.117]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1010.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[1]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1010.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[-1.148, 0, -5.627]} rotation={[0, 0, -0.128]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1009.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[3]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1009.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[-2.444, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1008.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[1.54, 0.333, 0.004]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[4]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1008.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[-1.789, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1007.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[5]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1007.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[0.174, 0, -5.627]} rotation={[0.012, 0.002, -0.35]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1006.geometry}
            material={materials['standardSurface1.004']}
            position={[0.05, -0.148, -5.046]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[6]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1006.geometry}
            material={materials['standardSurface1.004']}
            position={[0.05, -0.081, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
        <group position={[2.227, 0, -5.627]} rotation={[0, 0, -0.402]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1005.geometry}
            material={materials['standardSurface1.004']}
            position={[0, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[7]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1005.geometry}
            material={materials['standardSurface1.004']}
            position={[0, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
      </group>
      <group position={[-0.8, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[-4.411, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1014.geometry}
            material={materials['standardSurface1.005']}
            position={[-7.621, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[8]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1015.geometry}
            material={materials['standardSurface1.005']}
            position={[-7.621, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
      </group>
      <group position={[-0.8, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group scale={0.895}>
          <group position={[-4.93, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass014.geometry}
              material={materials['standardSurface1.006']}
              position={[-7.621, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
        </group>
      </group>
      <group position={[9.352, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[-4.411, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1015.geometry}
            material={materials['standardSurface1.007']}
            position={[1.53, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[10]} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1016.geometry}
            material={materials['standardSurface1.007']}
            position={[1.53, 0, -8.609]}
            scale={[0.045, 0.045, 2.366]}
          />
        </group>
      </group>
      <group position={[9.352, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group scale={0.895}>
          <group position={[-4.93, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass015.geometry}
              material={materials['standardSurface1.008']}
              position={[1.53, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
        </group>
      </group>
      <group position={[2.049, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support001.geometry}
          material={materials['standardSurface1.009']}
          position={[3.596, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
      </group>
      <group position={[-1.743, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Support1001.geometry}
          material={materials['standardSurface1.010']}
          position={[-4.54, 0, -1.677]}
          scale={[0.076, 0.087, 1.771]}
        />
      </group>
      <group position={[-0.366, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[-4.411, 0, -5.627]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper1016.geometry}
            material={materials['standardSurface1.012']}
            position={[0.163, -0.067, -5.047]}
            rotation={[Math.PI / 2, 0.49, 0]}
            scale={[0.846, 2.922, 0.979]}
          >
            <waveMaterial ref={waveRefs[14]} />
          </mesh>
        </group>
      </group>
      <group position={[-0.366, 0.661, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group scale={0.895}>
          <group position={[-4.93, 0, -6.288]} scale={0.112}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__Glass016.geometry}
              material={materials['standardSurface1.011']}
              position={[0, 0, -7.949]}
              scale={[1, 1, 0.927]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Temple.glb')
